# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
